puts "The students of my Academy"
puts "-------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vadar"
puts "Nurse Ratchet"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked WItch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
