puts "The students of my Academy"
puts "-------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vadar"
puts "Nurse Ratchet"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked WItch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
#Adding a summary total of students
print "Overall, we have "
print 11
puts " great students"
